name: Sanity check
on: [push, pull_request]

jobs:
  python-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python3 -m pip install -r ./requirements.txt

      - name: Install mypy
        run: |
          python3 -m pip install mypy types-requests

      - name: Check with mypy
        run: |
          python3 -m mypy --no-incremental staffeli_nt
